server:
  port: ${PORT:8085}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/med_db}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:12345678}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # Configuration upload de fichiers
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 50MB

  # Définit le préfixe de toutes les routes générées par Data REST
  data:
    rest:
      base-path: /api

  # Configuration Email (Gmail SMTP)
  mail:
    host: smtp.gmail.com
    port: 587
    username: tiomelajorel@gmail.com
    password: ${MAIL_PASSWORD:axgawninapjjxvfm}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

# Configuration personnalisée pour l'upload
app:
  upload:
    dir: uploads/images
  mail:
    from: tiomelajorel@gmail.com
    from-name: MED Auto

# Configuration JWT
jwt:
  secret: "MED-Application-Secret-Key-For-JWT-Token-Generation-2024-Must-Be-At-Least-256-Bits-Long"
  expiration: 86400000      # 24h pour clients/societes
  admin-expiration: 28800000 # 8h pour admin

