spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/med_db
    username: med_user
    password: med_password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Définit le préfixe de toutes les routes générées par Data REST
  data:
    rest:
          base-path: /api

# Pour que Swagger affiche aussi les routes de Data REST
springdoc:
  :show-data-rest: true