server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/med_db
    username: postgres
    password: 12345678

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

# Définit le préfixe de toutes les routes générées par Data REST
  data:
    rest:
          base-path: /api

